// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	IndividualSubscriptionDocumentAPIService := openapi.NewIndividualSubscriptionDocumentAPIService()
	IndividualSubscriptionDocumentAPIController := openapi.NewIndividualSubscriptionDocumentAPIController(IndividualSubscriptionDocumentAPIService)

	SubscriptionsCollectionCollectionAPIService := openapi.NewSubscriptionsCollectionCollectionAPIService()
	SubscriptionsCollectionCollectionAPIController := openapi.NewSubscriptionsCollectionCollectionAPIController(SubscriptionsCollectionCollectionAPIService)

	router := openapi.NewRouter(IndividualSubscriptionDocumentAPIController, SubscriptionsCollectionCollectionAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
