/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"
	"time"

	openapi "github.com/damejias23/test_C-DAF/go"
	"github.com/joho/godotenv"
	"github.com/kelseyhightower/envconfig"
)

type MainConfig struct {
	Server struct {
		Addr string `envconfig:"SERVER_ADDR"`
	}
}

func main() {

	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}
	var config MainConfig
	err = envconfig.Process("", &config)
	if err != nil {
		log.Fatal(err.Error())
	}
	// log.Printf("Server started")
	openapi.InitConfig()

	IndividualSubscriptionDocumentApiService := openapi.NewIndividualSubscriptionDocumentApiService()
	IndividualSubscriptionDocumentApiController := openapi.NewIndividualSubscriptionDocumentApiController(IndividualSubscriptionDocumentApiService)

	SubscriptionsCollectionCollectionApiService := openapi.NewSubscriptionsCollectionCollectionApiService()
	SubscriptionsCollectionCollectionApiController := openapi.NewSubscriptionsCollectionCollectionApiController(SubscriptionsCollectionCollectionApiService)

	router := openapi.NewRouter(IndividualSubscriptionDocumentApiController, SubscriptionsCollectionCollectionApiController)

	// log.Fatal(http.ListenAndServe(":8080", router))

	server := &http.Server{
		Addr:         config.Server.Addr,
		Handler:      router,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}
	log.Printf("Server listening at %s", config.Server.Addr)
	log.Fatal(server.ListenAndServe())

}
