/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	IndividualSubscriptionDocumentApiService := openapi.NewIndividualSubscriptionDocumentApiService()
	IndividualSubscriptionDocumentApiController := openapi.NewIndividualSubscriptionDocumentApiController(IndividualSubscriptionDocumentApiService)

	SubscriptionsCollectionCollectionApiService := openapi.NewSubscriptionsCollectionCollectionApiService()
	SubscriptionsCollectionCollectionApiController := openapi.NewSubscriptionsCollectionCollectionApiController(SubscriptionsCollectionCollectionApiService)

	router := openapi.NewRouter(IndividualSubscriptionDocumentApiController, SubscriptionsCollectionCollectionApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
