// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi

import (
	"context"
	"net/http"
)



// IndividualSubscriptionDocumentAPIRouter defines the required methods for binding the api requests to a responses for the IndividualSubscriptionDocumentAPI
// The IndividualSubscriptionDocumentAPIRouter implementation should parse necessary information from the http request,
// pass the data to a IndividualSubscriptionDocumentAPIServicer to perform the required actions, then write the service results to the http response.
type IndividualSubscriptionDocumentAPIRouter interface { 
	DeleteSubscription(http.ResponseWriter, *http.Request)
	ModifySubscription(http.ResponseWriter, *http.Request)
}
// SubscriptionsCollectionCollectionAPIRouter defines the required methods for binding the api requests to a responses for the SubscriptionsCollectionCollectionAPI
// The SubscriptionsCollectionCollectionAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SubscriptionsCollectionCollectionAPIServicer to perform the required actions, then write the service results to the http response.
type SubscriptionsCollectionCollectionAPIRouter interface { 
	CreateSubscription(http.ResponseWriter, *http.Request)
}


// IndividualSubscriptionDocumentAPIServicer defines the api actions for the IndividualSubscriptionDocumentAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IndividualSubscriptionDocumentAPIServicer interface { 
	DeleteSubscription(context.Context, string) (ImplResponse, error)
	ModifySubscription(context.Context, string, *ModifySubscriptionRequest) (ImplResponse, error)
}


// SubscriptionsCollectionCollectionAPIServicer defines the api actions for the SubscriptionsCollectionCollectionAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SubscriptionsCollectionCollectionAPIServicer interface { 
	CreateSubscription(context.Context, CdafCreateEventSubscription) (ImplResponse, error)
}
