/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// IndividualSubscriptionDocumentApiRouter defines the required methods for binding the api requests to a responses for the IndividualSubscriptionDocumentApi
// The IndividualSubscriptionDocumentApiRouter implementation should parse necessary information from the http request,
// pass the data to a IndividualSubscriptionDocumentApiServicer to perform the required actions, then write the service results to the http response.
type IndividualSubscriptionDocumentApiRouter interface { 
	DeleteSubscription(http.ResponseWriter, *http.Request)
	ModifySubscription(http.ResponseWriter, *http.Request)
}
// SubscriptionsCollectionCollectionApiRouter defines the required methods for binding the api requests to a responses for the SubscriptionsCollectionCollectionApi
// The SubscriptionsCollectionCollectionApiRouter implementation should parse necessary information from the http request,
// pass the data to a SubscriptionsCollectionCollectionApiServicer to perform the required actions, then write the service results to the http response.
type SubscriptionsCollectionCollectionApiRouter interface { 
	CreateSubscription(http.ResponseWriter, *http.Request)
}


// IndividualSubscriptionDocumentApiServicer defines the api actions for the IndividualSubscriptionDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IndividualSubscriptionDocumentApiServicer interface { 
	DeleteSubscription(context.Context, string) (ImplResponse, error)
	ModifySubscription(context.Context, string, ModifySubscriptionRequest) (ImplResponse, error)
}


// SubscriptionsCollectionCollectionApiServicer defines the api actions for the SubscriptionsCollectionCollectionApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SubscriptionsCollectionCollectionApiServicer interface { 
	CreateSubscription(context.Context, CdafCreateEventSubscription) (ImplResponse, error)
}
