// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// IndividualSubscriptionDocumentAPIService is a service that implements the logic for the IndividualSubscriptionDocumentAPIServicer
// This service should implement the business logic for every endpoint for the IndividualSubscriptionDocumentAPI API.
// Include any external packages or services that will be required by this service.
type IndividualSubscriptionDocumentAPIService struct {
}

// NewIndividualSubscriptionDocumentAPIService creates a default api service
func NewIndividualSubscriptionDocumentAPIService() *IndividualSubscriptionDocumentAPIService {
	return &IndividualSubscriptionDocumentAPIService{}
}

// DeleteSubscription - Ncdaf_EventExposure Unsubscribe service Operation
func (s *IndividualSubscriptionDocumentAPIService) DeleteSubscription(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update DeleteSubscription with the required logic for this service method.
	// Add api_individual_subscription_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(307, RedirectResponse{}) or use other options such as http.Ok ...
	// return Response(307, RedirectResponse{}), nil

	// TODO: Uncomment the next line to return response Response(308, RedirectResponse{}) or use other options such as http.Ok ...
	// return Response(308, RedirectResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(411, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(411, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(413, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(413, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(415, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(500, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(503, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteSubscription method not implemented")
}

// ModifySubscription - Ncdaf_EventExposure Subscribe Modify service Operation
func (s *IndividualSubscriptionDocumentAPIService) ModifySubscription(ctx context.Context, subscriptionId string, modifySubscriptionRequest *ModifySubscriptionRequest) (ImplResponse, error) {
	// TODO - update ModifySubscription with the required logic for this service method.
	// Add api_individual_subscription_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CdafUpdatedEventSubscription{}) or use other options such as http.Ok ...
	// return Response(200, CdafUpdatedEventSubscription{}), nil

	// TODO: Uncomment the next line to return response Response(307, RedirectResponse{}) or use other options such as http.Ok ...
	// return Response(307, RedirectResponse{}), nil

	// TODO: Uncomment the next line to return response Response(308, RedirectResponse{}) or use other options such as http.Ok ...
	// return Response(308, RedirectResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(411, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(411, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(413, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(413, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(415, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(429, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(500, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(503, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ModifySubscription method not implemented")
}
