/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"log"
	"net/http"
	"strings"
)

// SubscriptionsCollectionCollectionApiController binds http requests to an api service and writes the service results to the http response
type SubscriptionsCollectionCollectionApiController struct {
	service      SubscriptionsCollectionCollectionApiServicer
	errorHandler ErrorHandler
}

// SubscriptionsCollectionCollectionApiOption for how the controller is set up.
type SubscriptionsCollectionCollectionApiOption func(*SubscriptionsCollectionCollectionApiController)

// WithSubscriptionsCollectionCollectionApiErrorHandler inject ErrorHandler into controller
func WithSubscriptionsCollectionCollectionApiErrorHandler(h ErrorHandler) SubscriptionsCollectionCollectionApiOption {
	return func(c *SubscriptionsCollectionCollectionApiController) {
		c.errorHandler = h
	}
}

// NewSubscriptionsCollectionCollectionApiController creates a default api controller
func NewSubscriptionsCollectionCollectionApiController(s SubscriptionsCollectionCollectionApiServicer, opts ...SubscriptionsCollectionCollectionApiOption) Router {
	controller := &SubscriptionsCollectionCollectionApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SubscriptionsCollectionCollectionApiController
func (c *SubscriptionsCollectionCollectionApiController) Routes() Routes {
	return Routes{
		{
			"CreateSubscription",
			strings.ToUpper("Post"),
			"/ncdaf-evts/v1/subscriptions",
			c.CreateSubscription,
		},
	}
}

// CreateSubscription - Ncdaf_EventExposure Subscribe service Operation
func (c *SubscriptionsCollectionCollectionApiController) CreateSubscription(w http.ResponseWriter, r *http.Request) {
	cdafCreateEventSubscriptionParam := CdafCreateEventSubscription{}
	d := json.NewDecoder(r.Body)
	log.Println(d)
	d.DisallowUnknownFields()
	if err := d.Decode(&cdafCreateEventSubscriptionParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		log.Println("Error 12")
		return
	}
	if err := AssertCdafCreateEventSubscriptionRequired(cdafCreateEventSubscriptionParam); err != nil {
		c.errorHandler(w, r, err, nil)
		log.Println("Error 2")
		return
	}
	result, err := c.service.CreateSubscription(r.Context(), cdafCreateEventSubscriptionParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Println("Error 3")
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
