/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// IndividualSubscriptionDocumentApiService is a service that implements the logic for the IndividualSubscriptionDocumentApiServicer
// This service should implement the business logic for every endpoint for the IndividualSubscriptionDocumentApi API.
// Include any external packages or services that will be required by this service.
type IndividualSubscriptionDocumentApiService struct {
}

// NewIndividualSubscriptionDocumentApiService creates a default api service
func NewIndividualSubscriptionDocumentApiService() IndividualSubscriptionDocumentApiServicer {
	return &IndividualSubscriptionDocumentApiService{}
}

// DeleteSubscription - Ncdaf_EventExposure Unsubscribe service Operation
func (s *IndividualSubscriptionDocumentApiService) DeleteSubscription(ctx context.Context, subscriptionId string) (ImplResponse, error) {
	// TODO - update DeleteSubscription with the required logic for this service method.
	// Add api_individual_subscription_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteSubscription method not implemented")
}
