// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// CdafEventArea - Represents an area to be monitored by an CDAF event
type CdafEventArea struct {

	PresenceInfo PresenceInfo `json:"presenceInfo,omitempty"`
}

// AssertCdafEventAreaRequired checks if the required fields are not zero-ed
func AssertCdafEventAreaRequired(obj CdafEventArea) error {
	if err := AssertPresenceInfoRequired(obj.PresenceInfo); err != nil {
		return err
	}
	return nil
}

// AssertCdafEventAreaConstraints checks if the values respects the defined constraints
func AssertCdafEventAreaConstraints(obj CdafEventArea) error {
	return nil
}
