/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CdafEventType - Describes the supported event types of Ncadf_EventExposure Service
type CdafEventType string

// List of CdafEventTypeAnyOf
const (
	CDAFEVENT_REPORT_RESOURCE_USAGE CdafEventType = "REPORT_RESOURCE_USAGE"
)

// AssertCdafEventTypeRequired checks if the required fields are not zero-ed
func AssertCdafEventTypeRequired(obj CdafEventType) error {
	return nil
}

// AssertRecurseCdafEventTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CdafEventType (e.g. [][]CdafEventType), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCdafEventTypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCdafEventType, ok := obj.(CdafEventType)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCdafEventTypeRequired(aCdafEventType)
	})
}
