// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// NotificationFlag - Possible values are: - ACTIVATE: The event notification is activated. - DEACTIVATE: The event notification is deactivated and shall be muted. The available    event(s) shall be stored. - RETRIEVAL: The event notification shall be sent to the NF service consumer(s),   after that, is muted again.  
type NotificationFlag struct {
}

// AssertNotificationFlagRequired checks if the required fields are not zero-ed
func AssertNotificationFlagRequired(obj NotificationFlag) error {
	return nil
}

// AssertNotificationFlagConstraints checks if the values respects the defined constraints
func AssertNotificationFlagConstraints(obj NotificationFlag) error {
	return nil
}
