/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresenceStateAnyOf string

// List of PresenceStateAnyOf
const (
	IN_AREA PresenceStateAnyOf = "IN_AREA"
	OUT_OF_AREA PresenceStateAnyOf = "OUT_OF_AREA"
	UNKNOWN PresenceStateAnyOf = "UNKNOWN"
	INACTIVE PresenceStateAnyOf = "INACTIVE"
)

// AssertPresenceStateAnyOfRequired checks if the required fields are not zero-ed
func AssertPresenceStateAnyOfRequired(obj PresenceStateAnyOf) error {
	return nil
}

// AssertRecursePresenceStateAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresenceStateAnyOf (e.g. [][]PresenceStateAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresenceStateAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresenceStateAnyOf, ok := obj.(PresenceStateAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresenceStateAnyOfRequired(aPresenceStateAnyOf)
	})
}
