/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CdafCreateEventSubscription - Data within a create CDAF event subscription request
type CdafCreateEventSubscription struct {

	Subscription CdafEventSubscription `json:"subscription"`
}

// AssertCdafCreateEventSubscriptionRequired checks if the required fields are not zero-ed
func AssertCdafCreateEventSubscriptionRequired(obj CdafCreateEventSubscription) error {
	elements := map[string]interface{}{
		"subscription": obj.Subscription,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCdafEventSubscriptionRequired(obj.Subscription); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCdafCreateEventSubscriptionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CdafCreateEventSubscription (e.g. [][]CdafCreateEventSubscription), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCdafCreateEventSubscriptionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCdafCreateEventSubscription, ok := obj.(CdafCreateEventSubscription)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCdafCreateEventSubscriptionRequired(aCdafCreateEventSubscription)
	})
}
