// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// CdafEventSubscriptionInfo - Individual CDAF Event Subscription Information
type CdafEventSubscriptionInfo struct {

	// String providing an URI formatted according to RFC 3986.
	SubId string `json:"subId"`

	NotifyCorrelationId string `json:"notifyCorrelationId,omitempty"`

	// String providing an URI formatted according to RFC 3986.
	OldSubId string `json:"oldSubId,omitempty"`
}

// AssertCdafEventSubscriptionInfoRequired checks if the required fields are not zero-ed
func AssertCdafEventSubscriptionInfoRequired(obj CdafEventSubscriptionInfo) error {
	elements := map[string]interface{}{
		"subId": obj.SubId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCdafEventSubscriptionInfoConstraints checks if the values respects the defined constraints
func AssertCdafEventSubscriptionInfoConstraints(obj CdafEventSubscriptionInfo) error {
	return nil
}
