// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// CdafEventType - Describes the supported event types of Ncadf_EventExposure Service
type CdafEventType struct {
}

// AssertCdafEventTypeRequired checks if the required fields are not zero-ed
func AssertCdafEventTypeRequired(obj CdafEventType) error {
	return nil
}

// AssertCdafEventTypeConstraints checks if the values respects the defined constraints
func AssertCdafEventTypeConstraints(obj CdafEventType) error {
	return nil
}
