/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CdafEventTrigger - Describes how CDAF should generate the report for the event
type CdafEventTrigger string

const (
	EVENTTRIGGER_ONE_TIME   CdafEventTrigger = "ONE_TIME"
	EVENTTRIGGER_CONTINUOUS CdafEventTrigger = "CONTINUOUS"
	EVENTTRIGGER_PERIODIC   CdafEventTrigger = "PERIODIC"
)

// AssertCdafEventTriggerRequired checks if the required fields are not zero-ed
func AssertCdafEventTriggerRequired(obj CdafEventTrigger) error {
	return nil
}

// AssertRecurseCdafEventTriggerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CdafEventTrigger (e.g. [][]CdafEventTrigger), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCdafEventTriggerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCdafEventTrigger, ok := obj.(CdafEventTrigger)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCdafEventTriggerRequired(aCdafEventTrigger)
	})
}
