// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// CdafUpdateEventSubscriptionItem - Document describing the modification(s) to an CDAF Event Subscription
type CdafUpdateEventSubscriptionItem struct {

	Op string `json:"op"`

	Path string `json:"path"`

	Value CdafEvent `json:"value,omitempty"`

	PresenceInfo PresenceInfo `json:"presenceInfo,omitempty"`

	ExcludeSupiList []string `json:"excludeSupiList,omitempty"`

	ExcludeGpsiList []string `json:"excludeGpsiList,omitempty"`

	IncludeSupiList []string `json:"includeSupiList,omitempty"`

	IncludeGpsiList []string `json:"includeGpsiList,omitempty"`
}

// AssertCdafUpdateEventSubscriptionItemRequired checks if the required fields are not zero-ed
func AssertCdafUpdateEventSubscriptionItemRequired(obj CdafUpdateEventSubscriptionItem) error {
	elements := map[string]interface{}{
		"op": obj.Op,
		"path": obj.Path,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCdafEventRequired(obj.Value); err != nil {
		return err
	}
	if err := AssertPresenceInfoRequired(obj.PresenceInfo); err != nil {
		return err
	}
	return nil
}

// AssertCdafUpdateEventSubscriptionItemConstraints checks if the values respects the defined constraints
func AssertCdafUpdateEventSubscriptionItemConstraints(obj CdafUpdateEventSubscriptionItem) error {
	return nil
}
