// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




type ModifySubscriptionRequest struct {
}

// AssertModifySubscriptionRequestRequired checks if the required fields are not zero-ed
func AssertModifySubscriptionRequestRequired(obj ModifySubscriptionRequest) error {
	return nil
}

// AssertModifySubscriptionRequestConstraints checks if the values respects the defined constraints
func AssertModifySubscriptionRequestConstraints(obj ModifySubscriptionRequest) error {
	return nil
}
