/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CdafEventArea - Represents an area to be monitored by an CDAF event
type CdafEventArea struct {

	PresenceInfo PresenceInfo `json:"presenceInfo,omitempty"`
}

// AssertCdafEventAreaRequired checks if the required fields are not zero-ed
func AssertCdafEventAreaRequired(obj CdafEventArea) error {
	if err := AssertPresenceInfoRequired(obj.PresenceInfo); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCdafEventAreaRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CdafEventArea (e.g. [][]CdafEventArea), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCdafEventAreaRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCdafEventArea, ok := obj.(CdafEventArea)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCdafEventAreaRequired(aCdafEventArea)
	})
}
