// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// PartitioningCriteria - Possible values are: - \"TAC\": Type Allocation Code - \"SUBPLMN\": Subscriber PLMN ID - \"GEOAREA\": Geographical area, i.e. list(s) of TAI(s) - \"SNSSAI\": S-NSSAI - \"DNN\": DNN 
type PartitioningCriteria struct {
}

// AssertPartitioningCriteriaRequired checks if the required fields are not zero-ed
func AssertPartitioningCriteriaRequired(obj PartitioningCriteria) error {
	return nil
}

// AssertPartitioningCriteriaConstraints checks if the values respects the defined constraints
func AssertPartitioningCriteriaConstraints(obj PartitioningCriteria) error {
	return nil
}
