/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PartitioningCriteriaAnyOf string

// List of PartitioningCriteriaAnyOf
const (
	TAC PartitioningCriteriaAnyOf = "TAC"
	SUBPLMN PartitioningCriteriaAnyOf = "SUBPLMN"
	GEOAREA PartitioningCriteriaAnyOf = "GEOAREA"
	SNSSAI PartitioningCriteriaAnyOf = "SNSSAI"
	DNN PartitioningCriteriaAnyOf = "DNN"
)

// AssertPartitioningCriteriaAnyOfRequired checks if the required fields are not zero-ed
func AssertPartitioningCriteriaAnyOfRequired(obj PartitioningCriteriaAnyOf) error {
	return nil
}

// AssertRecursePartitioningCriteriaAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PartitioningCriteriaAnyOf (e.g. [][]PartitioningCriteriaAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePartitioningCriteriaAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPartitioningCriteriaAnyOf, ok := obj.(PartitioningCriteriaAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPartitioningCriteriaAnyOfRequired(aPartitioningCriteriaAnyOf)
	})
}
