/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Guami - Globally Unique AMF Identifier constructed out of PLMN, Network and AMF identity.
type Guami struct {

	PlmnId PlmnIdNid `json:"plmnId"`

	// String identifying the AMF ID composed of AMF Region ID (8 bits), AMF Set ID (10 bits) and AMF  Pointer (6 bits) as specified in clause 2.10.1 of 3GPP TS 23.003. It is encoded as a string of  6 hexadecimal characters (i.e., 24 bits).  
	AmfId string `json:"amfId"`
}

// AssertGuamiRequired checks if the required fields are not zero-ed
func AssertGuamiRequired(obj Guami) error {
	elements := map[string]interface{}{
		"plmnId": obj.PlmnId,
		"amfId": obj.AmfId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPlmnIdNidRequired(obj.PlmnId); err != nil {
		return err
	}
	return nil
}

// AssertRecurseGuamiRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Guami (e.g. [][]Guami), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGuamiRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGuami, ok := obj.(Guami)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGuamiRequired(aGuami)
	})
}
