/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CdafEventTypeAnyOf string

// List of CdafEventTypeAnyOf
const (
	PRESENCE_IN_AOI_REPORT CdafEventTypeAnyOf = "PRESENCE_IN_AOI_REPORT"
	TIMEZONE_REPORT CdafEventTypeAnyOf = "TIMEZONE_REPORT"
	ACCESS_TYPE_REPORT CdafEventTypeAnyOf = "ACCESS_TYPE_REPORT"
	REGISTRATION_STATE_REPORT CdafEventTypeAnyOf = "REGISTRATION_STATE_REPORT"
	CONNECTIVITY_STATE_REPORT CdafEventTypeAnyOf = "CONNECTIVITY_STATE_REPORT"
	REACHABILITY_REPORT CdafEventTypeAnyOf = "REACHABILITY_REPORT"
	COMMUNICATION_FAILURE_REPORT CdafEventTypeAnyOf = "COMMUNICATION_FAILURE_REPORT"
	UES_IN_AREA_REPORT CdafEventTypeAnyOf = "UES_IN_AREA_REPORT"
	SUBSCRIPTION_ID_CHANGE CdafEventTypeAnyOf = "SUBSCRIPTION_ID_CHANGE"
	SUBSCRIPTION_ID_ADDITION CdafEventTypeAnyOf = "SUBSCRIPTION_ID_ADDITION"
)

// AssertCdafEventTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertCdafEventTypeAnyOfRequired(obj CdafEventTypeAnyOf) error {
	return nil
}

// AssertRecurseCdafEventTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CdafEventTypeAnyOf (e.g. [][]CdafEventTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCdafEventTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCdafEventTypeAnyOf, ok := obj.(CdafEventTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCdafEventTypeAnyOfRequired(aCdafEventTypeAnyOf)
	})
}
