/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CdafEventTypeAnyOf string

// List of CdafEventTypeAnyOf
const (
	REPORT_RESOURCE_USAGE CdafEventTypeAnyOf = "REPORT_RESOURCE_USAGE"
)

// AssertCdafEventTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertCdafEventTypeAnyOfRequired(obj CdafEventTypeAnyOf) error {
	return nil
}

// AssertRecurseCdafEventTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CdafEventTypeAnyOf (e.g. [][]CdafEventTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCdafEventTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCdafEventTypeAnyOf, ok := obj.(CdafEventTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCdafEventTypeAnyOfRequired(aCdafEventTypeAnyOf)
	})
}
