// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// CdafEventTrigger - Describes how CDAF should generate the report for the event
type CdafEventTrigger struct {
}

// AssertCdafEventTriggerRequired checks if the required fields are not zero-ed
func AssertCdafEventTriggerRequired(obj CdafEventTrigger) error {
	return nil
}

// AssertCdafEventTriggerConstraints checks if the values respects the defined constraints
func AssertCdafEventTriggerConstraints(obj CdafEventTrigger) error {
	return nil
}
