// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// CdafEventSubsSyncInfo - CDAF Event Subscriptions Information for synchronization
type CdafEventSubsSyncInfo struct {

	SubscriptionList []CdafEventSubscriptionInfo `json:"subscriptionList"`
}

// AssertCdafEventSubsSyncInfoRequired checks if the required fields are not zero-ed
func AssertCdafEventSubsSyncInfoRequired(obj CdafEventSubsSyncInfo) error {
	elements := map[string]interface{}{
		"subscriptionList": obj.SubscriptionList,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.SubscriptionList {
		if err := AssertCdafEventSubscriptionInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCdafEventSubsSyncInfoConstraints checks if the values respects the defined constraints
func AssertCdafEventSubsSyncInfoConstraints(obj CdafEventSubsSyncInfo) error {
	return nil
}
