// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi


import (
	"time"
)



// CdafUpdateEventOptionItem - Document describing the modifications to CDAF event subscription options
type CdafUpdateEventOptionItem struct {

	Op string `json:"op"`

	Path string `json:"path"`

	// string with format 'date-time' as defined in OpenAPI.
	Value time.Time `json:"value"`

	NotifFlag NotificationFlag `json:"notifFlag,omitempty"`
}

// AssertCdafUpdateEventOptionItemRequired checks if the required fields are not zero-ed
func AssertCdafUpdateEventOptionItemRequired(obj CdafUpdateEventOptionItem) error {
	elements := map[string]interface{}{
		"op": obj.Op,
		"path": obj.Path,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNotificationFlagRequired(obj.NotifFlag); err != nil {
		return err
	}
	return nil
}

// AssertCdafUpdateEventOptionItemConstraints checks if the values respects the defined constraints
func AssertCdafUpdateEventOptionItemConstraints(obj CdafUpdateEventOptionItem) error {
	return nil
}
