// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ncdaf_EventExposure
 *
 * CDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.3
 */

package openapi




// PresenceState - Possible values are: -IN_AREA: Indicates that the UE is inside or enters the presence reporting area. -OUT_OF_AREA: Indicates that the UE is outside or leaves the presence reporting area -UNKNOW: Indicates it is unknown whether the UE is in the presence reporting area or not -INACTIVE: Indicates that the presence reporting area is inactive in the serving node.  
type PresenceState struct {
}

// AssertPresenceStateRequired checks if the required fields are not zero-ed
func AssertPresenceStateRequired(obj PresenceState) error {
	return nil
}

// AssertPresenceStateConstraints checks if the values respects the defined constraints
func AssertPresenceStateConstraints(obj PresenceState) error {
	return nil
}
